"""init

Revision ID: 53762413942d
Revises: 
Create Date: 2026-05-30 14:54:41.109444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53762413942d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_codes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'USED', 'SUSPENDED', 'REVOKED', name='accesscode_status'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('schedules',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('time', sa.String(length=5), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('alias', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('RESIDENT', 'ADMIN', 'RESEARCHER', 'VIEWER', name='user_role'), nullable=True),
    sa.Column('code_used', sa.String(), nullable=False),
    sa.Column('push_token', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alias')
    )
    op.create_table('notif_prefs',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('push01', sa.Boolean(), nullable=True),
    sa.Column('push02', sa.Boolean(), nullable=True),
    sa.Column('push03', sa.Boolean(), nullable=True),
    sa.Column('push04', sa.Boolean(), nullable=True),
    sa.Column('push05', sa.Boolean(), nullable=True),
    sa.Column('push06', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('reports',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('EMPTY', 'HALF', 'FULL', 'OVERFLOW', name='report_status'), nullable=False),
    sa.Column('photo_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reports')
    op.drop_table('notif_prefs')
    op.drop_table('users')
    op.drop_table('schedules')
    op.drop_table('access_codes')
    # ### end Alembic commands ###
